openapi: 3.0.3
info:
    title: Diary Service
    description: Service for Diary
    version: "1.0"
servers:
    - url: http://localhost:8000
paths:
    /signin:
        post:
            tags:
                - diary
            summary: Signin diary
            description: Creates a valid API token
            operationId: diary#Signin
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SigninRequestBody'
                        example:
                            email: Dicta dolores itaque accusamus ducimus distinctio ab.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Similique sint cupiditate id et enim.
                            example: Culpa pariatur in assumenda voluptatem rerum.
    /signup:
        post:
            tags:
                - diary
            summary: UserSignup diary
            operationId: diary#UserSignup
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserSignupRequestBody'
                        example:
                            email: Consequatur quis aperiam assumenda.
                            name: Eius voluptatem necessitatibus.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                type: string
                                format: binary
components:
    schemas:
        SigninRequestBody:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Aut commodi dolorem eligendi dolor nemo provident.
            example:
                email: Tempore incidunt.
            required:
                - email
        UserSignupRequestBody:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Modi est eos perspiciatis earum.
                name:
                    type: string
                    description: User name
                    example: Unde consequatur.
            example:
                email: Voluptatem laudantium voluptatem est.
                name: Impedit deserunt.
            required:
                - name
                - email
tags:
    - name: diary
