name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: diary_test
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_NAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - uses: actions/checkout@v3
      - name: migrate
        run: ./scripts/migrate.sh
      - name: go test
        run: go test -v ./...
